#services:
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017

#services:
#  mongo:
#    image: mongo
#    container_name: mongo
#    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
#    ports:
#      - "27017:27017"
#
#  mongo-init:
#    image: mongo
#    container_name: mongo-init
#    depends_on:
#      - mongo
#    entrypoint: [ "bash", "-c", "sleep 5 && mongosh --host mongo --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'" ]

services:

  mongo:
    image: mongo:4.0
    ports:
      - '27017:27017'
    command: ["--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017"]
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"localhost:27017\"}]}).ok || rs.status().ok" | mongo --host mongo:27017 --quiet) -eq 1
      #      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"127.0.0.1:27017\"}]}).ok || rs.status().ok" | mongo --host mongo:27017 --quiet) -eq 1
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5